### ISSUE TITLE
Create new neural network for transfer learning combining TrackR-CNN and HPE

### ISSUE THREAD

**Issue by tshiUCSB** [ucsb-ersp-2019/vis-Claire-Vision#16]
- [ ] set up ResNet for shared layers #22 
- [ ] connect HPE w/ ResNet #23
- [ ] connect TrackR-CNN w/ ResNet #24
